mutation CreateTeam($name: String!) {
  insert_teams(objects: { name: $name }) {
    returning {
      admin_id
      name
      id
    }
  }
}

# if the user wanna join, only the team leader can add a user

mutation CreateBoard($is_public: Boolean!, $team_id: uuid!) {
  insert_boards(objects: { is_public: $is_public, team_id: $team_id }) {
    returning {
      id
      created_at
      is_public
      user_id
      team_id
    }
  }
}

mutation CreateDetails($board_id: uuid!) {
  insert_board_details(objects: { board_id: $board_id }) {
    returning {
      id
      board_id
    }
  }
}

mutation UpdateDetails($id: uuid!, $changes: board_details_set_input) {
  update_board_details(where: { id: { _eq: $id } }, _set: $changes) {
    returning {
      id
    }
  }
}
