query GetBoardLibraries {
  board_details {
    id
    framework
    css_library
    ui_library
  }
}

query GetLastMessages($board_id: uuid, $from_ts: timestamptz) {
  comments(
    order_by: { updated_at: asc }
    where: { updated_at: { _gte: $from_ts }, board_id: { _eq: $board_id } }
  ) {
    id
    content
    user {
      name
      id
    }
    board_id
    updated_at
  }
}

query GetTeamInfo($id: uuid!, $user_id: String!) {
  teams_by_pk(id: $id) {
    team_boards {
      id
      team_board_detail {
        ui_library
        id
        linter
        framework
        formatter
        css_library
      }
    }
    boards(where: { is_public: { _eq: true }, _not: { user_id: { _eq: $user_id } } }) {
      id
      user {
        id
        name
      }
    }
  }
}

query GetMyBoardInTeam($team_id: uuid!, $user_id: String!) {
  boards(where: { _and: { team_id: { _eq: $team_id }, user_id: { _eq: $user_id } } }) {
    id
    is_public
    board_detail {
      id
      hygen
      framework
      formatter
      css_library
      created_at
      builder
      isGit
      lint_staged_husky
      linter
      manager
      ui_library
      updated_at
      volta
      vscode
    }
  }
}

query GetJoinedTeams($user_id: String!) {
  teams(where: { team_members: { user_id: { _eq: $user_id } } }) {
    id
    name
    team_members {
      user_id
    }
    admin_user {
      id
      name
    }
  }
}

query GetUserInfo($id: String!) {
  users_by_pk(id: $id) {
    id
    email
    github_url
    is_online
    image_url
    name
    twitter_url
  }
}

query GetTeamMember($team_id: uuid!) {
  team_member(where: { team_id: { _eq: $team_id } }) {
    users {
      id
      name
      email
      image_url
      github_url
      twitter_url
    }
  }
}
