subscription SubscribeMessage($board_id: uuid) {
  comments(
    limit: 1
    order_by: { updated_at: desc }
    where: { board_id: { _eq: $board_id } }
  ) {
    id
    content
    user {
      id
      email
    }
    board_id
    updated_at
  }
}
