query GetCssFrameworks($name: String!){ 
  topic(name:$name){
    name
    repositories(first:5, orderBy: {field: STARGAZERS, direction: DESC}, ){
      nodes{
        name
        description
        createdAt
        updatedAt
        url
      }
    }
  }
}