'use client'
import { ApolloProvider } from '@apollo/client'
import { UserProvider } from '@auth0/nextjs-auth0/client'
import './globals.css'
import { Inter } from 'next/font/google'
import { useState } from 'react'

import { createGqlHasuraClient } from '@/libs/graphql/client'

// import type { Metadata } from 'next'

// eslint-disable-next-line
const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const authToken = ''
  const [client] = useState(createGqlHasuraClient(authToken))
  return (
    <html lang='en'>
      <ApolloProvider client={client}>
        <UserProvider>
          <body className={inter.className}>{children}</body>
        </UserProvider>
      </ApolloProvider>
    </html>
  )
}
